export const DEFAULT_AREAS = ["Entire Property", "Upstairs", "Downstairs", "Outside", "Garage", "Outbuilding", "Yard"];

export const DEFAULT_ROOMS = [
    "Bedroom",
    "Master Bedroom",
    "Kitchen",
    "Bathroom",
    "Master Bathroom",
    "Living Room",
    "Dining Room",
    "Den",
    "Laundry Room",
    "Mud Room",
    "Closet",
    "Hallway",
    "Stairway",
    "Basement",
    "Attic",
    "Crawlspace",
    "Porch",
    "Deck",
    "Sunroom",
];

export const DEFAULT_TAGS = [
    "Electrical",
    "Plumbing",
    "HVAC",
    "Flooring",
    "Painting",
    "Drywall Repair",
    "Cleaning",
    "Insulation",
    "Appliance",
    "Siding",
    "Fascia",
    "Trim/Molding",
    "Roofing",
    "Landscaping",
    "Pest Control",
    "General",
    "Decorating",
    "Staging",
    "Window",
    "Door",
    "Driveway",
    "Walkway",
    "Fencing",
    "Mailbox",
    "Cabinets",
    "Countertops",
];
